apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nodeapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nodeapp
        tier: backend
        track: stable
    spec:
      containers:
        - name: blog
          image: "juanvallejo/node-app:latest"
          ports:
            - name: nodeapp
              containerPort: 8000
          imagePullPolicy: IfNotPresent 
